const EErrors = {
    ROUTING_ERROR: 1,
    INVALID_TYPE_ERROR: 2,
    USER_NOT_FOUND: 3,
    PRODUCT_NOT_FOUND: 4,
    INTERNAL_SERVER_ERROR: 5,
    DATABASE_ERROR: 6,
    CREATE_PRODUCT_ERROR: 7,
    ADD_TO_CART_ERROR: 8,    
    UPDATING_PRODUCT_ERROR: 9,
    TOKEN_EXPIRED: 10,
    INVALID_PASSWORD:11,
}

export default EErrors;