openapi: 3.0.1
info:
  title: Productos API
  description: API RESTful para gestionar productos
  version: 1.0.0
paths:
  /api/products:
    get:
      summary: Obtener todos los productos
      tags:
        - Productos
      responses:
        '200':
          description: Lista de productos obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor

    post:
      summary: Crear un nuevo producto
      tags:
        - Productos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/CreateProduct'
      responses:
        '201':
          description: Producto creado correctamente
        '500':
          description: Error interno del servidor

  /api/products/{pid}:
    get:
      summary: Obtener un producto por ID
      tags:
        - Productos
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto a obtener
          schema:
            type: string
      responses:
        '200':
          description: Detalles del producto obtenidos correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado
        '500':
          description: Error interno del servidor

    put:
      summary: Actualizar un producto por ID
      tags:
        - Productos
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto a actualizar
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/UpdateProduct'
      responses:
        '200':
          description: Producto actualizado correctamente
        '404':
          description: Producto no encontrado
        '500':
          description: Error interno del servidor

    delete:
      summary: Eliminar un producto por ID
      tags:
        - Productos
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto a eliminar
          schema:
            type: string
      responses:
        '204':
          description: Producto eliminado correctamente
        '404':
          description: Producto no encontrado
        '500':
          description: Error interno del servidor

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: ID del producto
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        thumbnail:
          type: string
          description: URL de la imagen del producto
        category:
          type: string
          description: Categoría del producto
        code:
          type: string
          description: Código del producto
        status:
          type: string
          description: Estado del producto

  requestBodies:
    CreateProduct:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
              description:
                type: string
              price:
                type: number
              thumbnail:
                type: string
              category:
                type: string
              code:
                type: string
              status:
                type: string

    UpdateProduct:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
              description:
                type: string
              price:
                type: number
              thumbnail:
                type: string
              category:
                type: string
              code:
                type: string
              status:
                type: string
