openapi: 3.0.1
info:
  title: Carrito de Compras API
  description: API RESTful para gestionar carritos de compras
  version: 1.0.0
paths:
  /api/carts:
    get:
      summary: Obtener todos los carritos
      tags:
        - Carritos
      responses:
        '200':
          description: Lista de carritos obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cart'
        '500':
          description: Error interno del servidor

  /api/carts/{cid}:
    get:
      summary: Obtener un carrito por ID
      tags:
        - Carritos
      parameters:
        - in: path
          name: cid
          required: true
          description: ID del carrito a obtener
          schema:
            type: string
      responses:
        '200':
          description: Detalles del carrito obtenidos correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: Carrito no encontrado
        '500':
          description: Error interno del servidor

    put:
      summary: Actualizar un carrito por ID
      tags:
        - Carritos
      parameters:
        - in: path
          name: cid
          required: true
          description: ID del carrito a actualizar
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                products:
                  type: array
                  items:
                    type: object
                    properties:
                      productId:
                        type: string
                      quantity:
                        type: integer
      responses:
        '200':
          description: Carrito actualizado correctamente
        '404':
          description: Carrito no encontrado
        '500':
          description: Error interno del servidor

    delete:
      summary: Eliminar un carrito por ID
      tags:
        - Carritos
      parameters:
        - in: path
          name: cid
          required: true
          description: ID del carrito a eliminar
          schema:
            type: string
      responses:
        '204':
          description: Carrito eliminado correctamente
        '404':
          description: Carrito no encontrado
        '500':
          description: Error interno del servidor

  /api/carts/{cid}/purchase:
    post:
      summary: Realizar una compra desde el carrito
      tags:
        - Carritos
      parameters:
        - in: path
          name: cid
          required: true
          description: ID del carrito a realizar la compra
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
      responses:
        '200':
          description: Compra realizada correctamente
        '404':
          description: Producto no encontrado en el carrito
        '500':
          description: Error interno del servidor

components:
  schemas:
    Cart:
      type: object
      properties:
        _id:
          type: string
          description: ID del carrito
        products:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
                description: ID del producto
              quantity:
                type: integer
                description: Cantidad del producto en el carrito
